add_newline = false
format = "$python$directory$git_branch$git_status$character"
command_timeout = 1000

[directory]
truncation_length = 0
truncate_to_repo = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[python]
format = '[\(${symbol}${version}\)]($style) '
